os: osx

before_install:
    - brew upgrade python coreutils
    - brew install --with-python libxml2
    - pip3 install virtualenv
    - virtualenv --python=python3.7 /tmp/venv

install:
    - /tmp/venv/bin/pip install --no-binary=pyuwsgi pyuwsgi

script:
  - . /tmp/venv/bin/activate
  - "for i in {1..30}; do date; gtimeout --preserve-status 5 pyuwsgi --master --buffer-size=1024; echo $?; done"
