os: osx

before_install:
    - brew upgrade python
    - brew install --with-python libxml2
    - pip3 install virtualenv
    - virtualenv --python=python3.7 /tmp/venv

install:
    - /tmp/venv/bin/pip install --no-binary=pyuwsgi pyuwsgi

script: "for i in {1..30}; do /tmp/venv/bin/pyuwsgi --master --buffer-size=1024 2>&1 | grep -i \"segmentation fault\" || echo ok; done"
